CONTRIBUTING.mdにテンプレのURLを入れる #28
first-contributions-ja/first-contributions-ja.github.io pull request #47
Opened 2024-03-16 13:44 UTC by kagomen

## 概要
CONTRIBUTING.mdにイシュー・プルリクテンプレートのURLを入れる #28

## 関連するIssue
closed #28 

## その他
URLの追加の他に、プルリクの作成ルールを追加しました。
CONTRIBUTING.mdは参加者ではなくメンター向けのガイドなので、プルリクはイシューに対して行う旨を記載しました。問題がありましたら教えてください！

2024-03-16 13:53 UTC, kagomen commented
## 参考
#43 pull requestテンプレートの追加
[リポジトリ用のプルリクエストテンプレートの作成](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[クエリ パラメーターを使って pull request を作成する](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request)

2024-03-16 15:01 UTC, pss-aileen commented
プルリクの件、試してみました。

簡単にまとめるとプルリクの画面で `?quick_pull=1&template=TEMPLATENAME.md` を追加する必要があります。
`?quick_pull=1` というクエリが必要みたいです。

- 参考
  - [クエリパラメータを使用してプルリクエストを作成する - GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request)

---

自分のリポジトリでプルリク方法試してみました。

- プルリクテンプレートディレクトリ
  - `.github/PULL_REQUEST_TEMPLATE/mentor.md`

# 手順（2パターン）

## パターン1
ブランチから確認してプルリクを作るパターン

- <img src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/4d9683f1-d055-4709-83c2-d4fe8b988758" width="400">
- 上記の `1 commit ahead` からプルリクを作成
- こちらのURLに飛ぶ `https://github.com/pss-aileen/practice-github/compare/main...test` 
- ![スクリーンショット 2024-03-16 22 44 03](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/2b486c65-7cd0-4002-a6aa-a832dc7e7c15)
- これに `?quick_pull=1&template=mentor.md` を追加
- `https://github.com/pss-aileen/practice-github/compare/main...test?quick_pull=1&template=mentor.md`
- 結果👇
- ![スクリーンショット 2024-03-16 22 44 03](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/e19742c2-63d5-4dcc-befc-2b2926857a62)

## パターン2
pull requestのタブから作るパターン

- pull requestのタブクリック、`New pull request`クリック
  - <img src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/47638811-9052-46e6-8723-0da631e69ffe" width="400">
  - <img src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/e479a1b4-1c0a-4fbd-8651-f72b4db14069" width="400">
- ここでブランチを選択
  - <img src="https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/459f3a75-ca08-47da-8601-39bac8b0294d" width="400">
- こちらのページが表示される
  - `https://github.com/pss-aileen/practice-github/compare/main...test`
  - ![スクリーンショット 2024-03-16 22 53 53](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/07131ee5-5265-4b55-a90a-5713d0b576c2)
- URLに `?quick_pull=1&template=mentor.md` を追加
- ![スクリーンショット 2024-03-16 22 54 33](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/9a9780b8-6391-4152-be9d-1a613517972f)

2024-03-16 15:21 UTC, pss-aileen requested changes
IssueのテンプレートOKだと思います！
pull requestの部分ご確認よろしくお願いします！

2024-03-16 15:21 UTC, pss-aileen commented on docs/CONTRIBUTING.md
> +  - 基本的にIssueに対してコードを作成し、プルリクエストを行う
> 基本的にIssueに対してコードを作成し、プルリクエストを行う

基本的にIssueに対して**ブランチ**を作成し、プルリクエストを行う

コード→ブランチのほうがよりわかりやすいかな？と思いました。
いかがでしょうか？

2024-03-16 15:21 UTC, pss-aileen commented on docs/CONTRIBUTING.md
> +    - [テンプレート](https://github.com/first-contributions-ja/first-contributions-ja.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE%20/pr.md?plain=1)
>   - テンプレートに沿って内容を作成
>     - [テンプレート](https://github.com/first-contributions-ja/first-contributions-ja.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE%20/pr.md?plain=1)

これを削除して、以下はいかがでしょうか？

---

- プルリクエスト作成画面のURL末尾に以下を追加する
  ```markdown
  ?quick_pull=1&template=pr.md
  ```

  - プルリク画面URL
    - `https://github.com/first-contributions-ja/first-contributions-ja.github.io/compare/main...branchname`
  - テンプレートを追加したURL
    - `https://github.com/first-contributions-ja/first-contributions-ja.github.io/compare/main...branchname?quick_pull=1&template=pr.md`

---

ちょっと試してないので、ここのリポジトリでちゃんと↑ができるかを試してみる必要があります。
これを試してできれば↑こんな感じで記述すれば良いかな？と思いました。

2024-03-16 16:20 UTC, kazzyfrog commented
@pss-aileen 
お手数ですが、お手隙の際にブランチ`fix/#45_delete_code_of_conduct`から、
テンプレを利用して、プルリクが作成できるか確認して頂いても良いでしょうか？

自分も個人のリポジトリで検証したときはできたのですが、このリポジトリでは上手く出来ない…

2024-03-16 16:31 UTC, kazzyfrog commented
あ、大変失礼いたしましたw
PULL_REQUEST_TEMPLATEサブディレクトリに、半角スペースが入っていました🙏

現在のパス：
> .github/PULL_REQUEST_TEMPLATE /pr.md

2024-03-16 16:35 UTC, pss-aileen commented
> PULL_REQUEST_TEMPLATEサブディレクトリに、半角スペースが入っていました🙏

なるほど...！！！
可能性ありですね...！

2024-03-16 16:39 UTC, pss-aileen commented
> お手数ですが、お手隙の際にブランチ`fix/#45_delete_code_of_conduct`から、
> テンプレを利用して、プルリクが作成できるか確認して頂いても良いでしょうか？

ちなみに一応ですが、私もこちらできませんでした🙇

2024-03-16 16:50 UTC, kazzyfrog commented
修正しました！
これで、使えるようになるのでは？と思っています！
#48

2024-03-16 16:59 UTC, kagomen commented on docs/CONTRIBUTING.md
> +  - 基本的にIssueに対してコードを作成し、プルリクエストを行う
レビューありがとうございます！
たしかに！そうですね。変更します！

2024-03-16 17:00 UTC, pss-aileen commented
![スクリーンショット 2024-03-17 0 59 31](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/7810b753-d29f-4b2f-b445-9fd66bb85855)
↓
![スクリーンショット 2024-03-17 0 59 45](https://github.com/first-contributions-ja/first-contributions-ja.github.io/assets/140990100/3e799c92-9c5e-4833-a897-fbe29fa61a62)

`https://github.com/first-contributions-ja/first-contributions-ja.github.io/compare/main...fix/%2345_delete_code_of_conduct?quick_pull=1&template=pr.md`

いけました〜〜〜！！！！

@kazzyfrog @kagomen

2024-03-16 17:05 UTC, kazzyfrog commented
お二人ともありがとうございます！！！🎉
お騒がせいたしました🙏

2024-03-16 17:21 UTC, kagomen commented
お二人ともありがとうございます！！！
Docs読んでも何が何だかで途方に暮れてました……😩
修正しますー！（やり方わからないので明日調べて修正リクエスト？します！）

2024-03-16 17:32 UTC, kazzyfrog commented
修正する際は、同じブランチで「 :bug: fix:~~」でコミット積んで、pushすれば、自動的にプルリクに反映されますよ！

2024-03-17 03:22 UTC, kagomen commented
そうなんですね、ありがとうございます🙏
今から取り掛かります！

2024-03-17 03:28 UTC, kagomen commented
修正しましたのでお時間のあるときに確認お願いします🙏

2024-03-17 06:47 UTC, pss-aileen commented on docs/CONTRIBUTING.md
> +  - 基本的にIssueに対してコードを作成し、プルリクエストを行う
確認しました！

2024-03-17 06:47 UTC, pss-aileen commented on docs/CONTRIBUTING.md
> +    - [テンプレート](https://github.com/first-contributions-ja/first-contributions-ja.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE%20/pr.md?plain=1)
こちらも確認しました！ありがとうございます！

2024-03-17 06:48 UTC, pss-aileen approved these changes
LGTM🧚‍♂️

2024-03-17 06:49 UTC, merged