イシューテンプレートの追加・削除
first-contributions-ja/first-contributions-ja.github.io pull request #72
Opened 2024-03-19 12:36 UTC by kagomen

## 概要

イシューテンプレートの追加・削除 

## 関連するIssue

closed #68 

## その他

内容の確認をお願いします。

## 参考

## 残課題

週報のテンプレートをIssueで作るか、Discussionsで作るか？

2024-03-19 17:35 UTC, pss-aileen requested changes
すごく細かい点なのですが、コメント追加いたしました！
ご確認よろしくお願いいたします！！

テンプレートの内容自体はOKだと思います！🙆‍♀️

2024-03-19 17:35 UTC, pss-aileen commented on .github/ISSUE_TEMPLATE/feat_tmpl.md
> +- [ ]
すごく細かいのですが
`- [ ]` の `[ ]` の後ろに半角空白を入れると良いかもしれません！
そうすると、もし何も入力してなくてもチェックマークにならないのと
半角空白を入力する手間がはぶけるかと思います！

2024-03-19 17:35 UTC, pss-aileen commented on .github/ISSUE_TEMPLATE/fix_templ.md
> +- [ ]
こちらも同じくです！

2024-03-20 03:15 UTC, kagomen commented on .github/ISSUE_TEMPLATE/feat_tmpl.md
> +- [ ]
たしかに！
ありがとうございます！✨

2024-03-20 04:15 UTC, pss-aileen commented on .github/ISSUE_TEMPLATE/feat_tmpl.md
> +- [ ]
あ、`- []`、後ろに半角空白いれてもチェックボックスになりませんでした...笑
なんとなくで言ってしまってすみません😱😱😱
なると思ってました....😱😱😱
文字が入るとチェックボックスになるようです

以下テスト...
- [ ] 
- [ ] あ

2024-03-20 04:16 UTC, pss-aileen commented on .github/ISSUE_TEMPLATE/feat_tmpl.md
> +- [ ]
ただ、半角空白は結果として入力の手間がはぶけるかと思うので、
問題がなければ半角空白追加した状態で良いかと思います！😂

2024-03-20 04:33 UTC, kagomen commented on .github/ISSUE_TEMPLATE/feat_tmpl.md
> +- [ ]
後ろに文字を記入しないとならないんですね…！

> ただ、半角空白は結果として入力の手間がはぶけるかと思うので

同感です！

2024-03-20 13:37 UTC, kazzyfrog approved these changes
変更も確認しました！
LGTM😇

2024-03-20 16:01 UTC, pss-aileen approved these changes
確認しました！🎉
ありがとうございます！！

2024-03-20 16:01 UTC, merged